# Question 1:
Create a numpy array starting from 2 till 50 with a stepsize of 3.

In [1]:
# importing numpy with alias name
import numpy as np

# creating a array using numpy arange
arr = np.arange(2, 50, 3)

# printing array
print(arr)

[ 2  5  8 11 14 17 20 23 26 29 32 35 38 41 44 47]


# Question - 2
Accept two lists of 5 elements each from the user. Convert them to numpy arrays. Concatenate these arrays and print it. Also sort these arrays and print it.

In [2]:
# importing numpy with alias name
import numpy as np

# creating a 2 empty list:
lst_1 = []
lst_2 = []

# getting values for lst_1 from user:
for i in range(5):
  x=int(input("\nEnter the value for lst_1 : "))
  lst_1.append(x)

# getting values for lst_2 from user:
for i in range(5):
  x=int(input("\nEnter the value for lst_2 : "))
  lst_2.append(x)

# converting list into array:
arr_1 = np.array(lst_1)
arr_2 = np.array(lst_2)

# concatenating 2 array:
arr = np.concatenate((arr_1, arr_2))
print("\nArray value for concatenated arr :",arr)

# sorting up concatenated array
sortArr = np.sort(arr)
print("\nSorted Array for concatenated arr :",sortArr)


Enter the value for lst_1 : 10

Enter the value for lst_1 : 20

Enter the value for lst_1 : 90

Enter the value for lst_1 : 40

Enter the value for lst_1 : 50

Enter the value for lst_2 : 60

Enter the value for lst_2 : 80

Enter the value for lst_2 : 70

Enter the value for lst_2 : 30

Enter the value for lst_2 : 100

Array value for concatenated arr : [ 10  20  90  40  50  60  80  70  30 100]

Sorted Array for concatenated arr : [ 10  20  30  40  50  60  70  80  90 100]


# Question - 3:
Write a code snippet to find the dimensions of a ndarray and its size.

In [3]:
# importing numpy
import numpy as np

# creating a 2d array
arr = np.array([[1,2,3],[1,3,5]])

# Printing array dimensions (axes)
print("\nDimensions in array : ", arr.ndim)
 
# Printing size of array
print("\nSize of array : ", arr.size)


Dimensions in array :  2

Size of array :  6


# Question 4:

How to convert a 1D array into a 2D array? Demonstrate with the help of a code snippet.

In [4]:
'''
    To convert a 1D array into a 2D array, we can use reshape(a, newshape, order='C').
    
    e.g arr = np.array([ [1,2,3,4,5,6,7,8,9] ]) 
        
        arr.shape O/P: (1, 9)
        
        arr.reshape(3,3)
        
        O/P: array([[1, 2, 3],
                    [4, 5, 6],
                    [7, 8, 9]])
    
'''

arr = np.array([ [1,2,3,4,5,6,7,8,9] ])

print(arr,arr.shape) 

print()

arr = arr.reshape(3,3) 

print(arr,arr.shape)

[[1 2 3 4 5 6 7 8 9]] (1, 9)

[[1 2 3]
 [4 5 6]
 [7 8 9]] (3, 3)


# Question - 5:
Consider two square numpy arrays. Stack them vertically and horizontally.

In [5]:
arr1 = np.array([ [1,1,1] , [2,2,2] , [3,3,3] ])
arr2 = np.array([ [4,4,4] , [5,5,5] , [6,6,6] ])
print(np.vstack((arr1,arr2))) # Stack the arrays in a row-wise sequence
print() 
print(np.hstack((arr1,arr2))) # Stack the arrays in a column-wise sequence

[[1 1 1]
 [2 2 2]
 [3 3 3]
 [4 4 4]
 [5 5 5]
 [6 6 6]]

[[1 1 1 4 4 4]
 [2 2 2 5 5 5]
 [3 3 3 6 6 6]]


# Question 6:
How to get unique items and counts of unique items?

In [6]:
arr = np.array([ [1,2,2] , [1,2,2] , [5,6,6] ])

print(np.unique(arr,return_counts=True))

(array([1, 2, 5, 6]), array([2, 4, 1, 2], dtype=int64))
